export const BURGEREK = [
    {
        id: 'bandita',
        name: 'Bandita',
        src: '/optimized_etelek/Bandita.webp',
        ing: 'Marhahúspogácsa, Cheddar sajt, Bacon, Jalapeno paprika, Chili szósz, savanyított lilahagyma, paradicsom, uborka, saláta, hamburgerszósz',
        description: "A Bandita burger a merész ízvilágot kedvelők számára készült. Marhahúspogácsa, cheddar sajt, bacon és jalapeno paprika izgalmas kombinációja a paradicsom, uborka és saláta frissességével harmonizál. Egy igazi ízorgia az ínyenceknek!",
        ar: '3290',
        category: 'burger',
    },
    {
        id: 'bekebiro',
        name: 'Békebíró',
        src: '/optimized_etelek/Bekebiro.webp',
        ing: 'Marhahúspogácsa, Bacon, Juhtúró, rántott hagymakarika, paradicsom, lilahagyma, saláta, hamburgerszósz',
        description: "A Békebíró burger a békesség és harmónia ízeivel. A marhahúspogácsa és bacon mellett a juhtúró és rántott hagymakarika különleges élményt kínálnak, amit a friss zöldségek tesznek teljessé.",
        ar: '3290',
        category: 'burger',
    },
    {
        id: 'csalo',
        name: 'Csaló',
        src: '/optimized_etelek/Csalo.webp',
        ing: 'Marhahúspogácsa, uborka, lilahagyma, csalamádé, hamburgerszósz',
        description: "A Csaló burger a hagyományos ízek szerelmeseinek készült. Marhahúspogácsa, uborka, lilahagyma és csalamádé harmonikusan kombinálódik a hamburgerszósszal, egy finom és otthonos élményt teremtve.",
        ar: '2690',
        category: 'burger',
    },
    {
        id: 'csirkefogo',
        name: 'Csirkefogó',
        src: '/optimized_etelek/Csirkefogo.webp',
        ing: 'Rántott csirkemell csíkok, rántott hagymakarika, paradicsom, uborka, saláta, majonéz',
        description: "A Csirkefogó burgerben rántott csirkemellcsíkok találkoznak a rántott hagymakarikával, paradicsommal és uborkával. A majonéz íze pedig tökéletesen kiegészíti az ételt, igazi kényeztetést nyújtva a csirkerajongóknak.",
        ar: '2890',
        category: 'burger',
    },
    {
        id: 'dagonya',
        name: 'Dagonya',
        src: '/optimized_etelek/Dagonya.webp',
        ing: 'Marhahúspogácsa, Cheddar sajt, Bacon, Grillezett Camembert, áfonyalekvár, paradicsom, uborka, lilahagyma, saláta, hamburgerszósz',
        description: "A Dagonya burger a marhahúspogácsa, cheddar sajt, bacon és grillezett Camembert ízletes kombinációjával ragadja magával a gourmet élvezetek kedvelőit. Az áfonyalekvár édes-savanykás ízvilága és a friss zöldségek tökéletes harmóniát teremtenek.",
        ar: '3990',
        category: 'burger',
    },
    {
        id: 'duplasajtburger',
        name: 'Dupla Sajtburger',
        src: '/optimized_etelek/Duplasajt.webp',
        ing: 'Marhahúspogácsa 2x, mustár, Cheddar sajt, csemege uborka, ketchup, bacon',
        description: "A Dupla Sajtburger a hús és sajt szerelmeseinek kedvence. Kétszeres marhahúspogácsa, dupla Cheddar sajt, mustár, csemegeuborka és bacon egy igazi ízletes és gazdag burgerélményt nyújt.",
        ar: '3890',
        category: 'burger',
    },
    {
        id: 'fish',
        name: 'Fish Burger',
        src: '/optimized_etelek/Fish.webp',
        ing: 'Rántott halfilé, savanyított lilahagyma, paradicsom, kapros szósz',
        description: "A Fish Burger a tenger gyümölcseinek kedvelőinek álma. Rántott halfilé, savanyított lilahagyma és kapros szósz egyedülálló ízvilágot teremt a friss paradicsommal kombinálva.",
        ar: '2890',
        category: 'burger',
    },
    {
        id: 'kacsa',
        name: 'Gourmet Kacsa Burger',
        src: '/optimized_etelek/Kacsa.webp',
        ing: 'Párolt almás lilakáposzta, tépett kacsahús, karamelizált grillezett alma, BBQ szósz',
        description: "Ez a fenséges burger a kacsa ínycsiklandó zamatát ötvözi az édes-savanyú ízek harmóniájával, egy igazi gasztronómiai élményt kínálva minden falatban.",
        ar: '4490',
        category: 'burger',
    },
    {
        id: 'lator',
        name: 'Lator',
        src: '/optimized_etelek/Lator.webp',
        ing: 'Marhahúspogácsa, Bacon, Cheddar sajt, savanyított lilahagyma, BBQ szósz, paradicsom, uborka, saláta, hamburgerszósz',
        description: "A Lator burger a marhahúspogácsa, bacon, cheddar sajt és BBQ szósz kombinációjával egy izgalmas ízélményt nyújt. A savanyított lilahagyma és a friss zöldségek tökéletesen kiegészítik ezt a különleges fogást.",
        ar: '2990',
        category: 'burger',
    },
    {
        id: 'pulledpork',
        name: 'Pulled Pork Burger',
        src: '/optimized_etelek/Pulled.webp',
        ing: 'Mézes mustár, csemege uborka, saláta, savanyított lilahagyma, paradicsom, pulled pork, rántott hagymakarika, BBQ',
        description: "A Pulled Pork Burger a tépett hús rajongóinak készült. A mézes mustárral és BBQ szósszal kombinált pulled pork különleges élményt nyújt, amit a csemegeuborka és rántott hagymakarika tesz teljessé.",
        ar: '3890',
        category: 'burger',
    },
    {
        id: 'roffencs',
        name: 'Röffencs Burger',
        src: '/optimized_etelek/Roffencs.webp',
        ing: 'Fokhagymás majonéz, sertés húspogácsa, bacon, madársaláta, paradicsom, lilahagyma',
        description: "Húsimádók álma: szaftos sertéshús pogácsa ropogós baconnel ölelkezve, friss zöldségekkel és pikáns fokhagymás majonézzel megkoronázva.",
        ar: '2990',
        category: 'burger',
    },
    {
        id: 'sajtburger',
        name: 'Sajtburger',
        src: '/optimized_etelek/Sajtburger.webp',
        ing: 'Marhahúspogácsa, mustár, Cheddar sajt, csemege uborka, ketchup',
        description: "A Sajtburger a klasszikus ízek szerelmeseinek készült. Marhahúspogácsa, csípős mustár, olvadó Cheddar sajt és ropogós csemegeuborka találkozása a hagyományos ketchuppal egy ízletes, otthonos élményt kínál.",
        ar: '2590',
        category: 'burger',
    },
    {
        id: 'sajtimado',
        name: 'Sajtimádó',
        src: '/optimized_etelek/Sajtimado.webp',
        ing: 'Marhahúspogácsa, bacon, füstölt paprikás cheddar sajtszósz, pirított hagyma, cheddar sajt, füstölt edami sajt, maasdamer sajt, lilahagyma, jalapeno paprika',
        description: "A Sajtimádó burger a sajtok és a húsok szerelmeseinek készült. Marhahúspogácsa, füstölt paprikás cheddar sajtszósz, pirított hagyma és különböző sajtok gazdagítják ezt az ételt, izgalmas ízélményt nyújtva.",
        ar: '3690',
        category: 'burger',
    },
    {
        id: 'szelhamos',
        name: 'Szélhámos',
        src: '/optimized_etelek/Szelhamos.webp',
        ing: 'Marhahúspogácsa 2x, Cheddar sajt 2x, Bacon, rántott hagymakarika, paradicsom, uborka, lilahagyma, káposztasaláta, hamburgerszósz',
        description: "A Szélhámos burger a nagy étvágyúak kedvence. Kétszeres marhahúspogácsa, dupla Cheddar sajt, bacon és rántott hagymakarika találkozása a paradicsommal és uborkával ellenállhatatlan élményt nyújt.",
        ar: '3990',
        category: 'burger',
    },
    {
        id: 'vegabb',
        name: 'Vegább Burger',
        src: '/optimized_etelek/Vegabb.webp',
        ing: 'Vega húspogácsa, rántott hagymakarika, paradicsom, saláta, juhtúró, kapros szósz',
        description: "A Vegább Burger a vegetáriánusoknak készült, tele friss zöldségekkel és ízletes vega húspogácsával. A rántott hagymakarikával és kapros szósszal gazdagítva kellemesen friss ízélményt kínál.",
        ar: '2890',
        category: 'burger',
    },
    {
        id: 'zsivany',
        name: 'Zsivány',
        src: '/optimized_etelek/Zsivany.webp',
        ing: '2x Marhahúspogácsa, lilahagyma lekvár (chutney), 2x cheddar, 2x bacon, pirított hagyma',
        description: "A Zsivány burger a marhahúspogácsa, lilahagyma lekvár, cheddar és bacon kombinációjával egyedülálló ízélményt kínál. A pirított hagyma különleges, ropogós élményt ad hozzá.",
        ar: '3990',
        category: 'burger',
    },
    {
        id: 'vega',
        name: 'Vega Burger',
        src: '/optimized_etelek/Vega.webp',
        ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
        description: "A Vega Burger a grillezett Camembert és áfonyalekvár izgalmas kombinációjával a vegetáriánusok kedvenc választása. Saláta, paradicsom, uborka és hamburgerszósz friss, üde ízélményt kínál.",
        ar: '2790',
        category: 'burger',
    },
    {
        id: 'utonallo',
        name: 'Útonálló Burger',
        src: '/optimized_etelek/Utonallo.webp',
        ing: 'Amerikai coleslow saláta, marhahúspogácsa, Cheddar sajt, pulled pork, rántott hagymakarika, BBQ szósz',
        description: "Az Útonálló Burger a marhahúspogácsa és a BBQ szósszal készített különleges élmény szerelmeseinek készült. A bacon és pirított hagyma találkozása a paradicsommal és uborkával egy ellenállhatatlan ízélményt kínál.",
        ar: '3990',
        category: 'burger',
    },
]

export const SNACKBOX = [
    {
        id: 'adria',
        name: 'Adria Box',
        src: '/optimized_etelek/AdriaBox.webp',
        ing: 'Vaslapon sült fokhagymás olívás garnélarák nyárs, tintahalkarika, ráktorpedó, ráktemptúra, gyöngyhagyma, kapros szósz + választható köret',
        description: "Az Adria Box a tenger gyümölcseinek kedvelőinek álma. Vaslapon sült fokhagymás olívás garnélarák, tintahalkarika és ráktorpedó egy ízletes kapros szósszal kombinálva az Adriai-tenger ízeit hozza közel.",
        ar: '3490',
        category: 'snackbox',
    },
    {
        id: 'camembert',
        name: 'Grillezett Camembert',
        src: '/optimized_etelek/Camambert.webp',
        ing: 'Áfonyalekvárral + választható köret',
        description: "A grillezett Camembert áfonyalekvárral egy különleges ízélményt kínál a sajtok kedvelőinek. A krémes sajt és az édes áfonya tökéletes párost alkotnak.",
        ar: '2990',
        category: 'snackbox',
    },
    {
        id: 'csibebox',
        name: 'Csibe Box',
        src: '/optimized_etelek/Csibebox.webp',
        ing: 'Vaslapon sült csirkemell + választható köret',
        description: "A Csibe Box a csirkehús szerelmeseinek készült. Vaslapon sült csirkemell és választható köret harmonikus kombinációja ízletes, tápláló étkezést kínál.",
        ar: '2990',
        category: 'snackbox',
    },
    {
        id: 'cordonbleu',
        name: 'Cordon Bleu',
        src: '/optimized_etelek/CordonBleu.webp',
        ing: 'Sajttal sonkával töltött csirkemell, rizs, tartármártás',
        description: "Klasszikus ínyencség újragondolva: ropogós bundában rejlő, sajttal és sonkával gazdagon töltött csirkemell, mellé könnyed rizs és selymes tartármártás - a tökéletes harmónia minden falatra.",
        ar: '3990',
        category: 'snackbox',
    },
    {
        id: 'csirkemellcsikok',
        name: 'Rántott csirkemell csíkok',
        src: '/optimized_etelek/Csirkemellcsikok.webp',
        ing: '+ választható köret',
        description: "A rántott csirkemell csíkok ropogós és ízletes falatokat kínálnak, amelyeket választható körettel egészíthet ki.",
        ar: '3490',
        category: 'snackbox',
    },
    {
        id: 'gyerekbox_mozarella',
        name: 'Gyerek Box - Rántott Mozarella',
        src: '/optimized_etelek/Gyerekbox_Mozarella.webp',
        ing: 'Rántott mozarella rudacskák, ketchup vagy majonéz + választható köret',
        description: "A Gyerek Box - Rántott Mozarella a gyerekek kedvence lehet. Rántott mozarella rudacskák és választható köret egy vidám és ízletes étkezést biztosít.",
        ar: '1990',
        category: 'snackbox',
    },
    {
        id: 'gyerekbox_csirkemell',
        name: 'Gyerek Box - Rántott Csirkemell',
        src: '/optimized_etelek/Gyerekbox_Csirkemell.webp',
        ing: 'Rántott csirkemell csíkok, ketchup vagy majonéz + választható köret',
        description: "A Gyerek Box - Rántott Csirkemell a gyerekek számára készült, rántott csirkemell csíkok és választható körettel. Egyszerű, de finom választás.",
        ar: '1990',
        category: 'snackbox',
    },
    {
        id: 'triobox',
        name: 'Trió Box',
        src: '/optimized_etelek/TrioBox.webp',
        ing: 'Rántott csirkeszárny, sörtésztás hagymakarika, füstölt mozzarella fánk, 2 választható szósz (BBQ, Édessavanyú, Majonéz, Ketchup)',
        description: "Kóstoljon bele a ropogós élvezetekbe: aranybarnára sült, zamatos csirkeszárnyak; sörben fürdött, csábítóan ropogós hagymakarikák; és krémes, füstös mozzarellával töltött, csodásan pufi fánkok - mind egy dobozban, két szabadon választható, ínycsiklandó mártogatóssal megkoronázva.",
        ar: '3990',
        category: 'snackbox',
    },
    {
        id: 'gyros',
        name: 'Vaslapos Gyros Tál',
        src: '/optimized_etelek/Gyros.webp',
        ing: 'Sültkrumpli, gyros hús, saláta, paradicsom, uborka, lilahagyma, lilakáposzta, kapros fokhagymás joghurt',
        description: "A Vaslapos Gyros Tál egy mediterrán ízvilágot kínál. Sültkrumpli, gyros hús, saláta és kapros fokhagymás joghurt egy harmonikus ízorgiát teremtenek.",
        ar: '3490',
        category: 'snackbox',
    },
    {
        id: 'gyros_gorog',
        name: 'Vaslapos Gyros Tál - Görög salátával',
        src: '/optimized_etelek/GyrosGorog.webp',
        ing: 'Sültkrumpli, gyros hús, görög saláta, kapros fokhagymás joghurt',
        description: "A Vaslapos Gyros Tál - Görög salátával a mediterrán ízek tökéletes kombinációját nyújtja. Gyros hús, görög salátával és kapros fokhagymás joghurttal igazi ízvilágot kínál.",
        ar: '3990',
        category: 'snackbox',
    },
    {
        id: 'gyros_pita',
        name: 'Gyros Pita',
        src: '/optimized_etelek/GyrosPita.webp',
        ing: 'Gyros hús, saláta, paradicsom, uborka, lilahagyma, joghurt vagy csípős öntet',
        description: "Görög klasszikus kézbe fogva: puha pitában ölelkező, fűszeres gyros hús friss zöldségekkel és lilakáposztával, megkoronázva választható öntettel - egy harapás, és máris az Égei-tenger partján érezheti magát.",
        ar: '1890',
        category: 'snackbox',
    },
    {
        id: 'nachos',
        name: 'Nachos A Moziból!',
        src: '/optimized_etelek/Nachos.webp',
        ing: 'Fűszeres tortilla chips, cheddar sajtszósz, salsa szósz, jalapeno paprika',
        description: "Filmélmény az ízlelőbimbóknak: ropogós tortilla chips-ek fürdőznek a selymes cheddar sajtszószban, megbolondítva pikáns BBQ ízzel, friss salsával és csípős jalapeno paprikával - a mozis nachos élmény, amit otthon is átélhet.",
        ar: '2590',
        category: 'snackbox',
    },
    {
        id: 'vega_pita',
        name: 'Vega Pita',
        src: '/optimized_etelek/FalafelPita.webp',
        ing: 'Falafel, saláta, paradicsom, uborka, lilahagyma, joghurt vagy csípős öntet',
        description: "Növényi finomság pitába zárva: ropogós falafelgolyók friss zöldségek és zamatos lilakáposzta társaságában, választható öntettel megbolondítva - ízkavalkád, ami még a húsimádókat is megtéríti.",
        ar: '1890',
        category: 'snackbox',
    },
    {
        id: 'halfile',
        name: 'Rántott Halfilé',
        src: '/optimized_etelek/Halfile.webp',
        ing: 'Rántott alaszkai tőkehalfilé, kapros mártással + választható köret',
        description: "A rántott halfilé a halak szerelmeseinek készült. Kapros mártással kombinálva friss, üde ízélményt kínál.",
        ar: '2990',
        category: 'snackbox',
    },
    {
        id: 'pulledbox',
        name: 'Pulled Pork Tál',
        src: '/optimized_etelek/PulledBox.webp',
        ing: 'Sültkrumpli, amerikai coleslaw saláta, pulled pork, rántott hagymakarika, jalapeno paprika, BBQ szósz',
        description: "A Pulled Pork Tál a pulled pork rajongóinak készült. Hasábburgonya, amerikai coleslaw saláta és pulled pork tépett hús egy ízletes, tápláló élményt kínál.",
        ar: '3790',
        category: 'snackbox',
    },
    {
        id: 'sajtbansult',
        name: 'Sajtban sült Box',
        src: '/optimized_etelek/SajtbansultBox.webp',
        ing: 'Philadelphiai sajtgolyók, rántott camembert, mozarella rudacskák, jalapenos krémsajtgolyók + választható köret',
        description: "A Sajtban sült Box a sajtok szerelmeseinek készült. Philadelphiai sajtgolyók, rántott camembert és mozarella rudacskák, jalapenos krémsajtgolyók választható körettel gazdagítják ezt a boxot.",
        ar: '2990',
        category: 'snackbox',
    },
    {
        id: 'utonallobox',
        name: 'Útonálló Box',
        src: '/optimized_etelek/UtonalloBox.webp',
        ing: 'Rántott karaj, vaslapon sült csirkemell filé, rántott hagymakarika, rántott camembert, tintahalkarika, választható szósz 2x, + választható köret',
        description: "Az Útonálló Box a sokoldalú ízek kedvelőinek készült. Rántott karaj, vaslapon sült csirkemell filé és rántott hagymakarika egy ízletes, változatos ételt kínál.",
        ar: '3990',
        category: 'snackbox',
    },
    {
        id: 'vegabox',
        name: 'Vega Box',
        src: '/optimized_etelek/VegaBox.webp',
        ing: 'Röszti burgonya, falafel, haggymakarika, mozzarella rudacska + választható köret',
        description: "A Vega Box a vegetáriánusok kedvenc választása. Bécsi szelet káposztasalátával és választható körettel nyújt egy kellemes, friss ízélményt.",
        ar: '2890',
        category: 'snackbox',
    },
    {
        id: 'wienerbox',
        name: 'Wiener Schintzel Box',
        src: '/optimized_etelek/WienerBox.webp',
        ing: 'Bécsi szelet káposztasalátával + választható köret',
        description: "A Wiener Schnitzel Box egy hagyományos ízvilágot kínál. Wiener schnitzel, káposztasalátával és választható körettel.",
        ar: '3490',
        category: 'snackbox',
    },
];

export const KORETEK = [
    {
        id: 'jazminrizs',
        name: 'Jázmin rizs',
        src: '/optimized_etelek/Jazminrizs.webp',
        ing: '',
        description: "A jázmin rizs egy finom és illatos köret, amely minden fogáshoz tökéletesen passzol.",
        ar: '1190',
        category: 'köret',
    },
    {
        id: 'hasabburgonya',
        name: 'Hasábburgonya',
        src: '/optimized_etelek/Hasab.webp',
        ing: '',
        description: "A hasábburgonya a klasszikus sült krumpli élményét kínálja, amely minden fogás mellé jól illik.",
        ar: '1090',
        category: 'köret',
    },
    {
        id: 'edesburgonya',
        name: 'Édesburgonya',
        src: '/optimized_etelek/Edesburgonya.webp',
        ing: '',
        description: "Az édesburgonya a klasszikus sült krumpli édesebb változata, amely különleges ízélményt kínál.",
        ar: '1490',
        category: 'köret',
    },
    {
        id: 'rosztiburgonya',
        name: 'Rösztiburgonya',
        src: '/optimized_etelek/Rosztiburgonya.webp',
        ing: '',
        description: "A rösztiburgonya egy ropogós burgonyaropogós, amely tökéletes köret bármilyen ételhez.",
        ar: '1190',
        category: 'köret',
    },
    {
        id: 'hagymakarikak',
        name: 'Rántott hagymakarika',
        src: '/optimized_etelek/Hagymakarika.webp',
        ing: '',
        description: "A rántott hagymakarika egy ropogós, ízletes köret, amely különleges ízt ad minden fogáshoz.",
        ar: '990',
        category: 'köret',
    }
];

export const SALATAK = [
    {
        id: 'coleslow',
        name: 'Coleslow káposztasaláta',
        src: '/optimized_etelek/Coleslow.webp',
        ing: '',
        description: "Frissítő crunch minden falatban: finomra szeletelt ropogós káposzta és édes sárgarépa ölelkezik selymes, enyhén pikáns majonézes öntettel - a tökéletes kísérője bármely főételnek, vagy önmagában is üdítő fogás.",
        ar: '990',
        category: 'saláta',
    },
    {
        id: 'kaposztasalata',
        name: 'Káposztasaláta',
        src: '/optimized_etelek/Kaposztasalata.webp',
        ing: '',
        description: "A káposztasaláta egy friss, ropogós saláta, amely minden ételhez kiválóan passzol.",
        ar: '790',
        category: 'saláta',
    },
    {
        id: 'tavaszicsalamade',
        name: 'Tavaszi Csalamádé',
        src: '/optimized_etelek/Tavaszicsalamade.webp',
        ing: '',
        description: "A Tavaszi Csalamádé egy friss és üde saláta, amely kellemesen ropogós falatokat kínál.",
        ar: '790',
        category: 'saláta',
    },
    {
        id: 'utonallosalata',
        name: 'Útonálló saláta',
        src: '/optimized_etelek/UtonalloSalata.webp',
        ing: 'Madársaláta, paradicsom, uborka, lilahagyma ezersziget öntet',
        description: "Az Útonálló saláta egy ízletes saláta, amely ezersziget öntettel kombinálva kellemes ízélményt kínál.",
        ar: '1490',
        category: 'saláta',
    },
    {
        id: 'gorogsalata',
        name: 'Görög saláta',
        src: '/optimized_etelek/GorogSalata.webp',
        ing: 'Uborka, paradicsom, lilahagyma, oliva bogyó, feta sajt, bazsalikom, olivaolaj',
        description: "A görög saláta a mediterrán ízek kedvelőinek készült. Uborka, koktélparadicsom, lilahagyma, oliva bogyó és feta sajt egy friss, ízletes kombinációt alkotnak.",
        ar: '1890',
        category: 'saláta',
    }
];

export const DESSZERTEK = [
    {
        id: 'szufle',
        name: 'Belga csokoládé szuflé',
        src: '/optimized_etelek/Szufle.webp',
        ing: 'Vanília fagylalttal, tejszínhabbal, karamellás öntettel',
        description: "A belga csokoládé szuflé egy ellenállhatatlan desszert. Vanília fagylalttal, tejszínhabbal és karamellás öntettel kínálja a belga csokoládé gazdag ízét.",
        ar: '1790',
        category: 'desszert',
    },
    {
        id: 'palacsinta',
        name: 'Palacsinta',
        src: '/optimized_etelek/Palacsinta.webp',
        ing: '2 db / adag (Áfonyalekváros, Kakaós Nutellás)',
        description: "A palacsinta egy klasszikus desszert, amely finom és lágyszívű ízvilággal rendelkezik. Az áfonyalekvárral és kakaós nutellával tökéletes választás édesszájúaknak.",
        ar: '1400',
        category: 'desszert',
    },
];

export const KINALAT = [
    ...BURGEREK,
    ...SNACKBOX,
    ...KORETEK,
    ...SALATAK,
    ...DESSZERTEK
  ];