export const KINALAT = [
    { //BURGEREK
    id: 'bandita',
    name: 'Bandita',
    src: '/optimized_etelek/Bandita.webp',
    ing: 'Marhahúspogácsa, Cheddar sajt, Bacon, Jalapeno paprika,Chili szósz, savanyított lilahagyma, paradicsom, uborka, saláta, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3290',
    category: 'burger',
    },
    {
    id: 'bekebiro',
    name: 'Békebíró',
    src: '/optimized_etelek/Bekebiro.webp',
    ing: 'Marhahúspogácsa, Bacon, Juhtúró, rántott hagymakarika, paradicsom, lilahagyma, saláta, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3290',
    category: 'burger',
    },
    {
    id: 'csalo',
    name: 'Csaló',
    src: '/optimized_etelek/Csalo.webp',
    ing: 'Marhahúspogácsa, uborka, lilahagyma, csalamádé,hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2690',
    category: 'burger',
    },
    {
    id: 'csirkefogo',
    name: 'Csirkefogó',
    src: '/optimized_etelek/Csirkefogo.webp',
    ing: 'Rántott csirkemellcsíkok, rántott hagymakarika,paradicsom, uborka, saláta, majonéz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2890',
    category: 'burger',
    },
    {
    id: 'dagonya',
    name: 'Dagonya',
    src: '/optimized_etelek/Dagonya.webp',
    ing: 'Marhahúspogácsa, Cheddar sajt, Bacon, Grillezett Camembert, áfonyalekvár, paradicsom, uborka, lilahagyma, saláta, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'burger',
    },
    {
    id: 'duplasajtburger',
    name: 'Dupla Sajtburger',
    src: '/optimized_etelek/Duplasajt.webp',
    ing: 'Marhahúspogácsa 2x, mustár, Cheddar sajt, csemegeuborka, ketchup, bacon',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3890',
    category: 'burger',
    },
    {
    id: 'fish',
    name: 'Fish Burger',
    src: '/optimized_etelek/Fish.webp',
    ing: 'Rántott halfilé, pikáns savanyított lilahagymával, friss paradicsom, ízletes kapros szósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2890',
    category: 'burger',
    },
    {
    id: 'lator',
    name: 'Lator',
    src: '/optimized_etelek/Lator.webp',
    ing: 'Marhahúspogácsa, Bacon, Cheddar sajt savanyított lilahagyma,BBQ szósz paradicsom, uborka, saláta,hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'burger',
    },
    {
    id: 'pulledpork',
    name: 'Pulled pork Burger',
    src: '/optimized_etelek/Pulled.webp',
    ing: 'Mézes mustár, csemegeuborka, saláta, savanyított lilahagyma, paradicsom, pulled pork, rántott hagymakarika, BBQ',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3890',
    category: 'burger',
    },
    {
    id: 'sajtburger',
    name: 'Sajtburger',
    src: '/optimized_etelek/Sajtburger.webp',
    ing: 'Marhahúspogácsa, csípős mustár, olvadó Cheddar sajt, ropogós csemegeuborka, hagyományos ketchup.',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2590',
    category: 'burger',
    },
    {
    id: 'sajtimado',
    name: 'Sajtimádó',
    src: '/optimized_etelek/Sajtimado.webp',
    ing: 'Marhahúspogácsa,füstölt paprikás cheddar sajtszósz, pirított hagyma, Cheddar sajt, füstölt edami sajt, maasdamer sajt, lilahagyma, jalapeno paprika',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3690',
    category: 'burger',
    },
    {
    id: 'szelhamos',
    name: 'Szélhámos',
    src: '/optimized_etelek/Szelhamos.webp',
    ing: 'Marhahúspogácsa 2x, Cheddar sajt 2x, Bacon, Rántott hagymakarika,paradicsom,uborka, lilahagyma, káposztasaláta,hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'burger',
    },
    {
    id: 'vegabb',
    name: 'Vegább Burger',
    src: '/optimized_etelek/Vegabb.webp',
    ing: 'Vega húspogácsa, rántott hagymakarika, paradicsom, saláta, juhtúró, kapros szósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2890',
    category: 'burger',
    },
    {
    id: 'zsivany',
    name: 'Zsivány',
    src: '/optimized_etelek/Zsivany.webp',
    ing: 'Marhahúspogácsa,lilahagyma lekvár(chutney) cheddar, bacon, pirított hagyma',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'burger',
    },
    {
    id: 'vega',
    name: 'Vega Burger',
    src: '/optimized_etelek/Vega.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2790',
    category: 'burger',
    },
    {
    id: 'utonallo',
    name: 'Útonálló Burger',
    src: '/optimized_etelek/Lator.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'burger',
    // KEP CSERE
    },
    { // SNACK BOX
    id: 'adria',
    name: 'Adria Box',
    src: '/optimized_etelek/AdriaBox.webp',
    ing: 'Vaslapon sült Fokhagymás olívás garnéla rák nyárs, tintahalkarika, ráktorpedó, (ráktemptúra), gyöngyhagyma, kapros szósz + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3490',
    category: 'snackbox',
    },
    {
    id: 'camambert',
    name: 'Grillezett Camambert',
    src: '/optimized_etelek/Camambert.webp',
    ing: ' áfonyalekvárral + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'snackbox',
    },
    {
    id: 'csibebox',
    name: 'Csibe Box',
    src: '/optimized_etelek/Csibebox.webp',
    ing: 'Vaslapon sült csirkemell + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'snackbox',
    },
    {
    id: 'csirkemellcsikok',
    name: 'Rántott csirkemellcsíkok',
    src: '/optimized_etelek/Csirkemellcsikok.webp',
    ing: '+választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3490',
    category: 'snackbox',
    },
    {
    id: 'gyerekbox_mozarella',
    name: 'Gyerek Box - Rántott Mozarella',
    src: '/optimized_etelek/Gyerekbox_Mozarella.webp',
    ing: 'Rántott mozarella rudacskák, ketchup vagy majonéz + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1990',
    category: 'snackbox',
    },
    {
    id: 'gyerekbox_csirkemell',
    name: 'Gyerek Box - Rántott Csirkemell',
    src: '/optimized_etelek/Gyerekbox_Csirkemell.webp',
    ing: 'Rántott csirkemell csíkok, ketchup vagy majonéz + választható köret ',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1990',
    category: 'snackbox',
    },
    {
    id: 'gyros',
    name: 'Vaslapos Gyros Tál',
    src: '/optimized_etelek/Gyros.webp',
    ing: 'Sültkrumpli, gyros hús, saláta, paradicsom, uborka, lilahagyma, lilakáposzta, kapros fokhagymás joghurt',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3490',
    category: 'snackbox',
    },
    {
    id: 'gyros_gorog',
    name: 'Vaslapos Gyros Tál - Görög salátával',
    src: '/optimized_etelek/Gyros2.webp',
    ing: 'Sültkrumpli, gyros hús, saláta, paradicsom, uborka, lilahagyma, lilakáposzta, kapros fokhagymás joghurt, görögsaláta',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'snackbox',
    // KEP CSERE
    },
    {
    id: 'halfile',
    name: 'Rántott Halfilé',
    src: '/optimized_etelek/Halfile.webp',
    ing: 'kapros mártással + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'snackbox',
    },
    {
    id: 'pulledbox',
    name: 'Pulled Pork Tál',
    src: '/optimized_etelek/PulledBox.webp',
    ing: 'Hasábburgonya, amerikai coleslow saláta, pulled pork tépett hús rántott hagymakarika, jalapeno paprika, BBQ szósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3790',
    category: 'snackbox',
    },
    {
    id: 'sajtbansult',
    name: 'Sajtban sült Box',
    src: '/optimized_etelek/SajtbansultBox.webp',
    ing: 'Philadelphiai sajtgolyók, rántott camembert, mozarella rudacskák, jalapenos krémsajtgolyók + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'snackbox',
    },
    {
    id: 'utonallobox',
    name: 'Útonálló Box',
    src: '/optimized_etelek/UtonalloBox.webp',
    ing: 'Rántott karaj, vaslapon sült csirkemell filé, rántott hagymakarika, rántott camembert, tintahalkarika, választható szósz 2x, + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'snackbox',
    },
    {
    id: 'vegabox',
    name: 'Vega Box',
    src: '/optimized_etelek/VegaBox.webp',
    ing: 'Bécsi szelet káposztasalátával + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2890',
    category: 'snackbox',
    },
    {
    id: 'wienerbox',
    name: 'Wiener Schintzel Box',
    src: '/optimized_etelek/WienerBox.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3490',
    category: 'snackbox',
    },
    { // KÖRETEK
    id: 'jazminrizs',
    name: 'Jázmin rizs',
    src: '/optimized_etelek/Jazminrizs.webp',
    ing: '',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1190',
    category: 'köret',
    },
    {
    id: 'hasabburgonya',
    name: 'Hasábburgonya',
    src: '/optimized_etelek/Hasab.webp',
    ing: '',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1090',
    category: 'köret',
    },
    {
    id: 'edesburgonya',
    name: 'Édes burgonya',
    src: '/optimized_etelek/Edesburgonya.webp',
    ing: '',
    description: "",
    ar: '1490',
    category: 'köret',
    },
    {
    id: 'rosztiburgonya',
    name: 'Rösztiburgonya',
    src: '/optimized_etelek/Rosztiburgonya.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "",
    ar: '1190',
    category: 'köret',
    },
    {
    id: 'hagymakarikak',
    name: 'Rántott hagymakarika',
    src: '/optimized_etelek/Hagymakarika.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '990',
    category: 'köret',
    },
    { // SALÁTÁK
    id: 'kaposztasalata',
    name: 'Káposztasaláta',
    src: '/optimized_etelek/Kaposztasalata2.webp',
    ing: '',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '790',
    category: 'saláta',
    },
    {
    id: 'tavaszicsalamade',
    name: 'Tavaszi Csalamádé',
    src: '/optimized_etelek/Tavaszicsalamade.webp',
    ing: '',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '790',
    category: 'saláta',
    },
    {
    id: 'utonallosalata',
    name: 'Útonálló saláta',
    src: '/optimized_etelek/UtonalloSalata.webp',
    ing: 'Ezersziget öntettel',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1490',
    category: 'saláta',
    },
    {
    id: 'gorogsalata',
    name: 'Görög saláta',
    src: '/optimized_etelek/GorogSalata.webp',
    ing: 'Uborka, koktélparadicsom, lilahagyma, oliva bogyó, feta sajt, bazsalikom, olivaolaj',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1890',
    category: 'saláta',
    },
    { // DESSZERTEK
    id: 'szufle',
    name: 'Belga csokoládé szuflé',
    src: '/optimized_etelek/Szufle.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Vanillia fagylaltal, tejszínhabbal, karamellás öntettel",
    ar: '1790',
    category: 'desszert',
    },
    {
    id: 'palacsinta',
    name: 'Palacsinta',
    src: '/optimized_etelek/Szufle.webp', //KEP CSERE
    ing: '2db / adag (Áfonyalekváros Kakaós Nutellás)',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1400',
    category: 'desszert',
    },
]

export const BURGEREK = [
    { //BURGEREK
    id: 'bandita',
    name: 'Bandita',
    src: '/optimized_etelek/Bandita.webp',
    ing: 'Marhahúspogácsa, Cheddar sajt, Bacon, Jalapeno paprika,Chili szósz, savanyított lilahagyma, paradicsom, uborka, saláta, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3290',
    category: 'burger',
    },
    {
    id: 'bekebiro',
    name: 'Békebíró',
    src: '/optimized_etelek/Bekebiro.webp',
    ing: 'Marhahúspogácsa, Bacon, Juhtúró, rántott hagymakarika, paradicsom, lilahagyma, saláta, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3290',
    category: 'burger',
    },
    {
    id: 'csalo',
    name: 'Csaló',
    src: '/optimized_etelek/Csalo.webp',
    ing: 'Marhahúspogácsa, uborka, lilahagyma, csalamádé,hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2690',
    category: 'burger',
    },
    {
    id: 'csirkefogo',
    name: 'Csirkefogó',
    src: '/optimized_etelek/Csirkefogo.webp',
    ing: 'Rántott csirkemellcsíkok, rántott hagymakarika,paradicsom, uborka, saláta, majonéz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2890',
    category: 'burger',
    },
    {
    id: 'dagonya',
    name: 'Dagonya',
    src: '/optimized_etelek/Dagonya.webp',
    ing: 'Marhahúspogácsa, Cheddar sajt, Bacon, Grillezett Camembert, áfonyalekvár, paradicsom, uborka, lilahagyma, saláta, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'burger',
    },
    {
    id: 'duplasajtburger',
    name: 'Dupla Sajtburger',
    src: '/optimized_etelek/Duplasajt.webp',
    ing: 'Marhahúspogácsa 2x, mustár, Cheddar sajt, csemegeuborka, ketchup, bacon',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3890',
    category: 'burger',
    },
    {
    id: 'fish',
    name: 'Fish Burger',
    src: '/optimized_etelek/Fish.webp',
    ing: 'Rántott halfilé, pikáns savanyított lilahagymával, friss paradicsom, ízletes kapros szósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2890',
    category: 'burger',
    },
    {
    id: 'lator',
    name: 'Lator',
    src: '/optimized_etelek/Lator.webp',
    ing: 'Marhahúspogácsa, Bacon, Cheddar sajt savanyított lilahagyma,BBQ szósz paradicsom, uborka, saláta,hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'burger',
    },
    {
    id: 'pulledpork',
    name: 'Pulled pork Burger',
    src: '/optimized_etelek/Pulled.webp',
    ing: 'Mézes mustár, csemegeuborka, saláta, savanyított lilahagyma, paradicsom, pulled pork, rántott hagymakarika, BBQ',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3890',
    category: 'burger',
    },
    {
    id: 'sajtburger',
    name: 'Sajtburger',
    src: '/optimized_etelek/Sajtburger.webp',
    ing: 'Marhahúspogácsa, csípős mustár, olvadó Cheddar sajt, ropogós csemegeuborka, hagyományos ketchup.',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2590',
    category: 'burger',
    },
    {
    id: 'sajtimado',
    name: 'Sajtimádó',
    src: '/optimized_etelek/Sajtimado.webp',
    ing: 'Marhahúspogácsa,füstölt paprikás cheddar sajtszósz, pirított hagyma, Cheddar sajt, füstölt edami sajt, maasdamer sajt, lilahagyma, jalapeno paprika',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3690',
    category: 'burger',
    },
    {
    id: 'szelhamos',
    name: 'Szélhámos',
    src: '/optimized_etelek/Szelhamos.webp',
    ing: 'Marhahúspogácsa 2x, Cheddar sajt 2x, Bacon, Rántott hagymakarika,paradicsom,uborka, lilahagyma, káposztasaláta,hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'burger',
    },
    {
    id: 'vegabb',
    name: 'Vegább Burger',
    src: '/optimized_etelek/Vegabb.webp',
    ing: 'Vega húspogácsa, rántott hagymakarika, paradicsom, saláta, juhtúró, kapros szósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2890',
    category: 'burger',
    },
    {
    id: 'zsivany',
    name: 'Zsivány',
    src: '/optimized_etelek/Zsivany.webp',
    ing: 'Marhahúspogácsa,lilahagyma lekvár(chutney) cheddar, bacon, pirított hagyma',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'burger',
    },
    {
    id: 'vega',
    name: 'Vega Burger',
    src: '/optimized_etelek/Vega.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2790',
    category: 'burger',
    },
    {
    id: 'utonallo',
    name: 'Útonálló Burger',
    src: '/optimized_etelek/Lator.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'burger',
    // KEP CSERE
    }
]

export const SNACKBOX = [
    { // SNACK BOX
    id: 'adria',
    name: 'Adria Box',
    src: '/optimized_etelek/AdriaBox.webp',
    ing: 'Vaslapon sült Fokhagymás olívás garnéla rák nyárs, tintahalkarika, ráktorpedó, (ráktemptúra), gyöngyhagyma, kapros szósz + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3490',
    category: 'snackbox',
    },
    {
    id: 'camambert',
    name: 'Grillezett Camambert',
    src: '/optimized_etelek/Camambert.webp',
    ing: ' áfonyalekvárral + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'snackbox',
    },
    {
    id: 'csibebox',
    name: 'Csibe Box',
    src: '/optimized_etelek/Csibebox.webp',
    ing: 'Vaslapon sült csirkemell + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'snackbox',
    },
    {
    id: 'csirkemellcsikok',
    name: 'Rántott csirkemellcsíkok',
    src: '/optimized_etelek/Csirkemellcsikok.webp',
    ing: '+választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3490',
    category: 'snackbox',
    },
    {
    id: 'gyerekbox_mozarella',
    name: 'Gyerek Box - Rántott Mozarella',
    src: '/optimized_etelek/Gyerekbox_Mozarella.webp',
    ing: 'Rántott mozarella rudacskák, ketchup vagy majonéz + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1990',
    category: 'snackbox',
    },
    {
    id: 'gyerekbox_csirkemell',
    name: 'Gyerek Box - Rántott Csirkemell',
    src: '/optimized_etelek/Gyerekbox_Csirkemell.webp',
    ing: 'Rántott csirkemell csíkok, ketchup vagy majonéz + választható köret ',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1990',
    category: 'snackbox',
    },
    {
    id: 'gyros',
    name: 'Vaslapos Gyros Tál',
    src: '/optimized_etelek/Gyros.webp',
    ing: 'Sültkrumpli, gyros hús, saláta, paradicsom, uborka, lilahagyma, lilakáposzta, kapros fokhagymás joghurt',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3490',
    category: 'snackbox',
    },
    {
    id: 'gyros_gorog',
    name: 'Vaslapos Gyros Tál - Görög salátával',
    src: '/optimized_etelek/Gyros2.webp',
    ing: 'Sültkrumpli, gyros hús, saláta, paradicsom, uborka, lilahagyma, lilakáposzta, kapros fokhagymás joghurt, görögsaláta',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'snackbox',
    // KEP CSERE
    },
    {
    id: 'halfile',
    name: 'Rántott Halfilé',
    src: '/optimized_etelek/Halfile.webp',
    ing: 'kapros mártással + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'snackbox',
    },
    {
    id: 'pulledbox',
    name: 'Pulled Pork Tál',
    src: '/optimized_etelek/PulledBox.webp',
    ing: 'Hasábburgonya, amerikai coleslow saláta, pulled pork tépett hús rántott hagymakarika, jalapeno paprika, BBQ szósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3790',
    category: 'snackbox',
    },
    {
    id: 'sajtbansult',
    name: 'Sajtban sült Box',
    src: '/optimized_etelek/SajtbansultBox.webp',
    ing: 'Philadelphiai sajtgolyók, rántott camembert, mozarella rudacskák, jalapenos krémsajtgolyók + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2990',
    category: 'snackbox',
    },
    {
    id: 'utonallobox',
    name: 'Útonálló Box',
    src: '/optimized_etelek/UtonalloBox.webp',
    ing: 'Rántott karaj, vaslapon sült csirkemell filé, rántott hagymakarika, rántott camembert, tintahalkarika, választható szósz 2x, + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3990',
    category: 'snackbox',
    },
    {
    id: 'vegabox',
    name: 'Vega Box',
    src: '/optimized_etelek/VegaBox.webp',
    ing: 'Bécsi szelet káposztasalátával + választható köret',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '2890',
    category: 'snackbox',
    },
    {
    id: 'wienerbox',
    name: 'Wiener Schintzel Box',
    src: '/optimized_etelek/WienerBox.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '3490',
    category: 'snackbox',
    }
]

export const KORETEK = [
   
    { // KÖRETEK
    id: 'jazminrizs',
    name: 'Jázmin rizs',
    src: '/optimized_etelek/Jazminrizs.webp',
    ing: '',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1190',
    category: 'köret',
    },
    {
    id: 'hasabburgonya',
    name: 'Hasábburgonya',
    src: '/optimized_etelek/Hasab.webp',
    ing: '',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1090',
    category: 'köret',
    },
    {
    id: 'edesburgonya',
    name: 'Édes burgonya',
    src: '/optimized_etelek/Edesburgonya.webp',
    ing: '',
    description: "",
    ar: '1490',
    category: 'köret',
    },
    {
    id: 'rosztiburgonya',
    name: 'Rösztiburgonya',
    src: '/optimized_etelek/Rosztiburgonya.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "",
    ar: '1190',
    category: 'köret',
    },
    {
    id: 'hagymakarikak',
    name: 'Rántott hagymakarika',
    src: '/optimized_etelek/Hagymakarika.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '990',
    category: 'köret',
    }
]

export const SALATAK = [
    { // SALÁTÁK
    id: 'kaposztasalata',
    name: 'Káposztasaláta',
    src: '/optimized_etelek/Kaposztasalata2.webp',
    ing: '',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '790',
    category: 'saláta',
    },
    {
    id: 'tavaszicsalamade',
    name: 'Tavaszi Csalamádé',
    src: '/optimized_etelek/Tavaszicsalamade.webp',
    ing: '',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '790',
    category: 'saláta',
    },
    {
    id: 'utonallosalata',
    name: 'Útonálló saláta',
    src: '/optimized_etelek/UtonalloSalata.webp',
    ing: 'Ezersziget öntettel',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1490',
    category: 'saláta',
    },
    {
    id: 'gorogsalata',
    name: 'Görög saláta',
    src: '/optimized_etelek/GorogSalata.webp',
    ing: 'Uborka, koktélparadicsom, lilahagyma, oliva bogyó, feta sajt, bazsalikom, olivaolaj',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1890',
    category: 'saláta',
    }
]

export const DESSZERTEK = [
    { // DESSZERTEK
    id: 'szufle',
    name: 'Belga csokoládé szuflé',
    src: '/optimized_etelek/Szufle.webp',
    ing: 'Grillezett Camembert, áfonyalekvár, saláta, paradicsom, uborka, lilahagyma, hamburgerszósz',
    description: "Vanillia fagylaltal, tejszínhabbal, karamellás öntettel",
    ar: '1790',
    category: 'desszert',
    },
    {
    id: 'palacsinta',
    name: 'Palacsinta',
    src: '/optimized_etelek/Szufle.webp', //KEP CSERE
    ing: '2db / adag (Áfonyalekváros Kakaós Nutellás)',
    description: "Lorem Ipsum is simply dummy text of the  printing and typesetting industry. Lorem Ipsum has been the industry's  standard dummy text ever since the 1500s.",
    ar: '1400',
    category: 'desszert',
    },
]