import Navbar from '@/components/Navbar';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* Add Navbar at the top */}
                <Navbar />
                {/* Render the children content */}
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
